#!/usr/bin/env python3
"""
appcast.py — generate a Sparkle-compatible appcast.xml for Chronio releases.

Usage:
    python3 scripts/package/appcast.py \\
        --version 1.2.0 \\
        --dmg dist/Chronio.dmg \\
        --private-key Frameworks/.sparkle_keys/sparkle_private_key \\
        [--output appcast.xml]

The generated appcast.xml should be published at the URL set in aw.spec's
SUFeedURL info_plist key (default: https://raw.githubusercontent.com/
MaxSchollum/ActivityChronio/master/appcast.xml).

Requires:
    • sign_update tool bundled with Sparkle.framework (at
      Frameworks/Sparkle.framework/Versions/B/Resources/sign_update).
    • The Ed25519 private key generated by setup_sparkle.sh.
"""

import argparse
import hashlib
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

REPO = "https://github.com/MaxSchollum/ActivityChronio"
RELEASES = f"{REPO}/releases/download"
APPCAST_URL = (
    "https://raw.githubusercontent.com/MaxSchollum/ActivityChronio/master/appcast.xml"
)
CHANNEL_TITLE = "Chronio"
CHANNEL_LINK = REPO

SIGN_UPDATE = str(
    Path(__file__).resolve().parent.parent.parent
    / "Frameworks"
    / "Sparkle.framework"
    / "Versions"
    / "B"
    / "Resources"
    / "sign_update"
)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _ed_signature(dmg: Path, private_key: Path) -> str:
    if not os.path.isfile(SIGN_UPDATE):
        print(
            f"WARNING: sign_update not found at {SIGN_UPDATE}. "
            "Run scripts/package/setup_sparkle.sh first.",
            file=sys.stderr,
        )
        return "PLACEHOLDER_SIGNATURE"
    result = subprocess.run(
        [SIGN_UPDATE, str(dmg), "--account", "com.maxschollum.chronio",
         "--private-key-file", str(private_key)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"sign_update failed: {result.stderr}")
    # sign_update prints "sparkle:edSignature=XXX length=YYY"
    for part in result.stdout.split():
        if part.startswith("sparkle:edSignature="):
            return part.split("=", 1)[1]
    raise RuntimeError(f"Unexpected sign_update output: {result.stdout!r}")


def generate_appcast(
    version: str,
    dmg: Path,
    private_key: Path,
    out: Path,
) -> None:
    size = dmg.stat().st_size
    pub_date = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S %z")
    download_url = f"{RELEASES}/v{version}/{dmg.name}"
    ed_sig = _ed_signature(dmg, private_key)

    rss = ET.Element("rss", {
        "version": "2.0",
        "xmlns:sparkle": "http://www.andymatuschak.org/xml-namespaces/sparkle",
        "xmlns:dc": "http://purl.org/dc/elements/1.1/",
    })
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = CHANNEL_TITLE
    ET.SubElement(channel, "link").text = CHANNEL_LINK
    ET.SubElement(channel, "description").text = f"{CHANNEL_TITLE} auto-update feed"
    ET.SubElement(channel, "language").text = "en"

    item = ET.SubElement(channel, "item")
    ET.SubElement(item, "title").text = f"Version {version}"
    ET.SubElement(item, "pubDate").text = pub_date
    ET.SubElement(item, "sparkle:version").text = version
    ET.SubElement(item, "sparkle:shortVersionString").text = version
    ET.SubElement(item, "sparkle:minimumSystemVersion").text = "12.0"

    enclosure = ET.SubElement(item, "enclosure")
    enclosure.set("url", download_url)
    enclosure.set("length", str(size))
    enclosure.set("type", "application/octet-stream")
    enclosure.set("sparkle:edSignature", ed_sig)

    tree = ET.ElementTree(rss)
    ET.indent(tree, space="  ")
    tree.write(str(out), encoding="utf-8", xml_declaration=True)
    print(f"Wrote {out}")
    print(f"  version:     {version}")
    print(f"  download:    {download_url}")
    print(f"  size:        {size:,} bytes")
    print(f"  edSignature: {ed_sig[:24]}…")


def main() -> None:
    p = argparse.ArgumentParser(description="Generate Chronio appcast.xml")
    p.add_argument("--version", required=True, help="Release version, e.g. 1.2.0")
    p.add_argument("--dmg", required=True, type=Path, help="Path to Chronio.dmg")
    p.add_argument(
        "--private-key",
        default=Path("Frameworks/.sparkle_keys/sparkle_private_key"),
        type=Path,
        help="Path to Sparkle Ed25519 private key file",
    )
    p.add_argument(
        "--output",
        default=Path("appcast.xml"),
        type=Path,
        help="Output path (default: appcast.xml)",
    )
    args = p.parse_args()

    if not args.dmg.exists():
        print(f"ERROR: DMG not found: {args.dmg}", file=sys.stderr)
        sys.exit(1)

    generate_appcast(args.version, args.dmg, args.private_key, args.output)


if __name__ == "__main__":
    main()
