"""
sparkle.py — Sparkle auto-update integration for Chronio.

Loads Sparkle.framework from the bundle (or from the repo-level Frameworks/
directory during development) and initialises SPUStandardUpdaterController,
which handles the complete update lifecycle: feed polling, download, delta
patching, and relaunch.

Requires:
  • PyObjC (pyobjc-framework-Cocoa) — already a dependency of aw-qt on macOS.
  • Sparkle.framework present at one of the search paths below.
  • SUFeedURL set in the app's Info.plist (wired via aw.spec).
  • SUPublicEDKey set in Info.plist (generated by Sparkle's generate_keys tool;
    see scripts/package/setup_sparkle.sh).

When the framework is absent (Linux, Windows, or a dev checkout without the
framework) this module is a no-op.  The Python-based fallback in updater.py
still shows an "Update available" menu item.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

_updater_controller: Optional[object] = None


def _sparkle_framework_path() -> Optional[Path]:
    """
    Find Sparkle.framework in order of preference:

    1. Inside the running .app bundle  (Contents/Frameworks/Sparkle.framework)
    2. Repo-level Frameworks/ directory (dev / CI build before packaging)
    """
    if sys.platform != "darwin":
        return None

    exe = Path(sys.executable).resolve()

    # 1. Bundle-internal: .../Chronio.app/Contents/MacOS/aw-qt
    bundle_fw = exe.parent.parent / "Frameworks" / "Sparkle.framework"
    if bundle_fw.exists():
        return bundle_fw

    # 2. Repo root: ../../../../Frameworks/Sparkle.framework
    #    (trayicon.py lives in aw-qt/aw_qt/, so four levels up = repo root)
    repo_root = Path(__file__).resolve().parent.parent.parent
    repo_fw = repo_root / "Frameworks" / "Sparkle.framework"
    if repo_fw.exists():
        return repo_fw

    return None


def init_sparkle() -> bool:
    """
    Initialise Sparkle and start the automatic update scheduler.

    Returns True on success, False if the framework is unavailable or
    initialisation fails.  Safe to call from the main thread after the
    QApplication is created.
    """
    global _updater_controller

    if sys.platform != "darwin":
        return False

    fw_path = _sparkle_framework_path()
    if fw_path is None:
        return False

    try:
        import objc  # type: ignore[import]

        objc.loadBundle(
            "Sparkle",
            bundle_path=str(fw_path),
            module_globals=globals(),
        )

        # SPUStandardUpdaterController is the recommended high-level entry
        # point in Sparkle 2.x.  Passing True to startingUpdater starts the
        # background feed-check scheduler immediately.
        ctrl = SPUStandardUpdaterController.alloc()  # type: ignore[name-defined]  # noqa: F821
        ctrl = ctrl.initWithStartingUpdater_updaterDelegate_userDriverDelegate_(
            True, None, None
        )
        _updater_controller = ctrl
        return True

    except Exception as exc:
        print(f"[chronio] Sparkle init failed: {exc}", file=sys.stderr)
        return False


def check_for_updates_now() -> bool:
    """
    Trigger an immediate user-facing update check (equivalent to
    "Check for Updates…" in a menu bar app).

    Returns True if Sparkle is active and the check was triggered,
    False if Sparkle was not initialised (caller should fall back to
    opening the releases page in the browser).
    """
    if _updater_controller is None:
        return False
    try:
        _updater_controller.checkForUpdates_(None)  # type: ignore[attr-defined]
        return True
    except Exception:
        return False
